### PR TITLE
Allow reading via xrootd

### PR DESCRIPTION
**Pull request by mburkart**

### CODE REVIEW

**Review by harrypuuter — COMMENTED** [review]
looks good! 

Three small questions:

* is this black-styled? if not yet, should we add this to the whole repo (in another pr)
* did you try the changes with validate_samples = True ?
* did you try it with uncertainty shifts?

**Comment by mburkart** [comment]
Concerning your questions:
* I think you black-styled the repository already in commits 0daaf05a80f6f505bcee93f2afff66999a213cbb and 04c5dec91727ae99cc6119b77ff441577323cf5d. The new parts should also be black styled but I will have a look again to check.
* I have not tried the validation yet, but I will have a look.
* I haven't tried yet, but the shifts should not make a difference as they are independent from the way the root file is read. I will check to be on the save side though.

**Comment by mburkart** [comment]
It seems like the names of the commits referenced above a slightly misleading and only small parts of the code are reformatted. I will open a pull request introducing the changes from black once this pull request is merged.

**Comment by harrypuuter** [comment]
looks fine, i suggest to merge this :)

**Pull request merged**
